// Secure Cloudflare Pages R2 media endpoint. Route: /media
// Files are public only through MEDIA_PUBLIC_URL (an R2 custom domain), never through credentials.
export interface Env { JWT_SECRET: string; MEDIA_BUCKET: R2Bucket; MEDIA_INDEX: KVNamespace; MEDIA_PUBLIC_URL?: string; }
const COOKIE_NAME = 'bmbcc_admin';
const HARD_LIMIT = 7 * 1024 ** 3;
const WARNING_LIMIT = 5 * 1024 ** 3;
type Category = 'images' | 'bulletins' | 'galleries' | 'logos' | 'qrcodes';
type Record = { key:string; size:number; category:Category; contentType:string; uploadedAt:string; trash?:boolean; trashAt?:string };
function json(body: unknown, status=200) { return new Response(JSON.stringify(body), {status, headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}); }
function token(cookie:string|null) { return cookie?.match(new RegExp(`${COOKIE_NAME}=([^;]+)`))?.[1]; }
async function admin(request:Request, env:Env) {
  if (!env.JWT_SECRET || !env.MEDIA_BUCKET || !env.MEDIA_INDEX) return false;
  const value=token(request.headers.get('Cookie')); if (!value) return false;
  try { const [h,p,s]=value.split('.'); if (!h||!p||!s) return false; const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.JWT_SECRET),{name:'HMAC',hash:'SHA-256'},false,['verify']); const sig=Uint8Array.from(atob((s+'='.repeat((4-s.length%4)%4)).replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)); if (!await crypto.subtle.verify('HMAC',key,sig,new TextEncoder().encode(`${h}.${p}`))) return false; const payload=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob((p+'='.repeat((4-p.length%4)%4)).replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)))); return payload.admin===true && (!payload.exp || payload.exp >= Math.floor(Date.now()/1000)); } catch { return false; }
}
function signature(bytes:Uint8Array, kind:string) { const s=(i:number)=>bytes[i]; if(kind==='pdf') return new TextDecoder().decode(bytes.slice(0,5))==='%PDF-'; if(kind==='image') return (s(0)===0xff&&s(1)===0xd8&&s(2)===0xff)||(s(0)===0x89&&new TextDecoder().decode(bytes.slice(1,4))==='PNG')||(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'); return false; }
function imageType(bytes:Uint8Array) { if(bytes[0]===0xff&&bytes[1]===0xd8) return 'image/jpeg'; if(bytes[0]===0x89) return 'image/png'; return 'image/webp'; }
function category(value:FormDataEntryValue|null):Category|null { return ['images','bulletins','galleries','logos','qrcodes'].includes(String(value)) ? String(value) as Category : null; }
async function records(env:Env):Promise<Record[]> { return (await env.MEDIA_INDEX.get('records','json') as Record[] | null)||[]; }
async function save(env:Env, value:Record[]) { await env.MEDIA_INDEX.put('records',JSON.stringify(value)); }
function usage(value:Record[]) { const live=value.filter(x=>!x.trash); const byCategory=Object.fromEntries(['images','bulletins','galleries','logos','qrcodes'].map(c=>[c,live.filter(x=>x.category===c).reduce((n,x)=>n+x.size,0)])); return {used:live.reduce((n,x)=>n+x.size,0), count:live.length, byCategory, warning:live.reduce((n,x)=>n+x.size,0)>=WARNING_LIMIT, hardLimit:HARD_LIMIT, warningLimit:WARNING_LIMIT}; }
export const onRequestOptions:PagesFunction<Env>=async()=>new Response(null,{status:204,headers:{'Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Cache-Control':'no-store'}});
export const onRequestGet:PagesFunction<Env>=async({request,env})=>{ if(!await admin(request,env)) return json({ok:false,error:'Not authenticated'},401); const all=await records(env); const u=usage(all); return json({ok:true,...u,remaining:Math.max(0,HARD_LIMIT-u.used),files:all.map(x=>({...x,url:env.MEDIA_PUBLIC_URL?`${env.MEDIA_PUBLIC_URL.replace(/\/$/,'')}/${x.key}`:null}))}); };
export const onRequestPost:PagesFunction<Env>=async({request,env})=>{ if(!await admin(request,env)) return json({ok:false,error:'Not authenticated'},401); try { const form=await request.formData(); const file=form.get('file'); const cat=category(form.get('category')); if(!(file instanceof File)||!cat) return json({ok:false,error:'A file and valid category are required.'},400); const pdf=cat==='bulletins'; if(pdf ? file.size>15*1024*1024 : file.size>(cat==='galleries'?8:cat==='logos'||cat==='qrcodes'?2:5)*1024*1024) return json({ok:false,error:'File exceeds this category’s pre-processing size limit.'},413); const bytes=new Uint8Array(await file.arrayBuffer()); if(!signature(bytes,pdf?'pdf':'image')) return json({ok:false,error:pdf?'Only real PDF files beginning with %PDF- are accepted.':'Only JPEG, PNG, and WebP images with a valid file signature are accepted.'},415); const type=pdf?'application/pdf':imageType(bytes); const all=await records(env); if(usage(all).used+bytes.byteLength>HARD_LIMIT) return json({ok:false,error:'Upload blocked: the 7 GB R2 storage limit would be exceeded.'},413); const now=new Date(); const ym=`${now.getUTCFullYear()}/${String(now.getUTCMonth()+1).padStart(2,'0')}`; const prefix=pdf?'bulletins':cat==='galleries'?'galleries/events':cat==='images'?'images/website':`images/${cat}`; const extension=pdf?'pdf':type==='image/jpeg'?'jpg':type==='image/png'?'png':'webp'; const key=`${prefix}/${ym}/${crypto.randomUUID()}.${extension}`; await env.MEDIA_BUCKET.put(key,bytes,{httpMetadata:{contentType:type,cacheControl:'public, max-age=31536000, immutable',contentDisposition:pdf?'inline':undefined},customMetadata:{category:cat,uploadedAt:now.toISOString()}}); const row:Record={key,size:bytes.byteLength,category:cat,contentType:type,uploadedAt:now.toISOString()}; all.push(row); await save(env,all); const base=env.MEDIA_PUBLIC_URL?.replace(/\/$/,''); if(!base) return json({ok:false,error:'Upload stored but MEDIA_PUBLIC_URL is not configured. Ask an administrator to configure the R2 custom media domain.'},500); return json({ok:true,url:`${base}/${key}`,file:row,usage:usage(all)}); } catch(e) { console.error(e); return json({ok:false,error:'Upload failed. Please try again.'},500); } };
// Deletion is deliberately a reversible trash action; permanent deletion is a future reviewed maintenance task.
export const onRequestDelete:PagesFunction<Env>=async({request,env})=>{ if(!await admin(request,env)) return json({ok:false,error:'Not authenticated'},401); const {key}=await request.json() as {key?:string}; const all=await records(env); const found=all.find(x=>x.key===key); if(!found) return json({ok:false,error:'Media not found'},404); found.trash=true; found.trashAt=new Date().toISOString(); await save(env,all); return json({ok:true,message:'Moved to trash. The object remains available for 30 days pending manual review.'}); };
